my:
  app:
    name: properties from git cloud config repo
    list: Hello,World,TEST
    map: "{connection:'https://github.com',host:'git',port:'6969'}"

db:
  connection: git-connection-test-from-config-server
  host: git
  port: 6969
