my:
  app:
    name: properties from config sever updated
    list: Hello,World,TEST
    map: "{connection:'https://____',host:'111',port:'8111'}"

db:
  connection: connection-test-from-config-server
  host: 111
  port: 8111
